name: Wordle GitHub Contributions

on:
  schedule:
    # at 08:00 UTC on the 1st of every month
    - cron: "0 8 1 * *"

jobs:
  tweet-contribution-grid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vchrombie/wordle-github-contributions@master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
